# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GeJl-egjifcVy6vOu4STbBIfMoFzfHtp
"""

print("Program list")
list_saya =[]
jalankan_program = True

while(jalankan_program):
  print('1. Tambahkan data ke List')
  print('2. Tampilkan data ke List')
  print('3. Hapus data ke List')
  print('4. Hitung jumlah data ke List')
  print('5. Cetak data ke List')
  print('6. Mengganti data ke List')
  print('7. Tampilkan data list terbesar ke terkecil')
  print('99. Hentikan program')
  nomor_menu = input('Pilih menu yang diinginkan: ')

  if(int(nomor_menu)== 1):
    data_input = input('Masukkan data ke list: ')
    list_saya.append(data_input)
  if(int(nomor_menu)== 2):
    print(list_saya)
  if(int(nomor_menu)== 3):
    list_saya.clear()
  if(int(nomor_menu)== 4):
    print('Jumlah data: ' + str(len(list_saya)))
  if(int(nomor_menu)== 5):
    for data in list_saya:
      print(data)
  if(int(nomor_menu)== 6):
    data_input = input('Masukkan data ke list: ')
    list_saya[0] = data_input
  if(int(nomor_menu)== 7):
    list_saya.sort(reverse=True)
    print(list_saya)
  if(int(nomor_menu)== 99):
    jalankan_program = False
print('Program selesai dijalankan')

"""# New Section"""